#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔑 Injecting verifying key into Stylus contract...');

// Read the verification key (from project root)
const vkPath = path.join(__dirname, '..', 'circuits', 'build', 'verification_key.json');
if (!fs.existsSync(vkPath)) {
  console.error('❌ Verification key not found. Run circuit build first.');
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(vkPath, 'utf8'));
console.log('✅ Loaded verification key');

// Convert VK to raw bytes format for Rust
function pointToBytes(point) {
  const x = BigInt(point[0]).toString(16).padStart(64, '0');
  const y = BigInt(point[1]).toString(16).padStart(64, '0');
  return `[${hexToByteArray(x).join(', ')}, ${hexToByteArray(y).join(', ')}]`;
}

function g2PointToBytes(point) {
  const x0 = BigInt(point[0][0]).toString(16).padStart(64, '0');
  const x1 = BigInt(point[0][1]).toString(16).padStart(64, '0');
  const y0 = BigInt(point[1][0]).toString(16).padStart(64, '0');
  const y1 = BigInt(point[1][1]).toString(16).padStart(64, '0');
  
  return `[${hexToByteArray(x0).join(', ')}, ${hexToByteArray(x1).join(', ')}, ${hexToByteArray(y0).join(', ')}, ${hexToByteArray(y1).join(', ')}]`;
}

function hexToByteArray(hex) {
  const bytes = [];
  for (let i = 0; i < hex.length; i += 2) {
    bytes.push(`0x${hex.substr(i, 2)}`);
  }
  return bytes;
}

// Generate Rust code for hardcoded VK
const alphaG1 = pointToBytes(vk.vk_alpha_1);
const betaG2 = g2PointToBytes(vk.vk_beta_2);
const gammaG2 = g2PointToBytes(vk.vk_gamma_2);
const deltaG2 = g2PointToBytes(vk.vk_delta_2);

let gammaAbcG1 = '[';
for (let i = 0; i < vk.IC.length; i++) {
  gammaAbcG1 += pointToBytes(vk.IC[i]);
  if (i < vk.IC.length - 1) gammaAbcG1 += ', ';
}
gammaAbcG1 += ']';

// Generate the complete verifying_key.rs file
const rustVkCode = `// Auto-generated verifying key implementation
// Generated by scripts/inject-vk.js - DO NOT EDIT MANUALLY

use crate::{G1Point, G2Point, ZKMintContract};
use alloy_primitives::U256;

// Hardcoded verifying key constants
const HARDCODED_VK_ALPHA_G1: G1Point = ${alphaG1};
const HARDCODED_VK_BETA_G2: G2Point = ${betaG2};
const HARDCODED_VK_GAMMA_G2: G2Point = ${gammaG2};
const HARDCODED_VK_DELTA_G2: G2Point = ${deltaG2};
const HARDCODED_VK_GAMMA_ABC_G1: &[G1Point] = &${gammaAbcG1};

impl ZKMintContract {
    pub fn set_hardcoded_verifying_key(&mut self) -> Result<(), Vec<u8>> {
        // Store alpha G1
        let alpha_x_bytes: [u8; 32] = HARDCODED_VK_ALPHA_G1[0..32].try_into().unwrap();
        let alpha_y_bytes: [u8; 32] = HARDCODED_VK_ALPHA_G1[32..64].try_into().unwrap();
        self.vk_alpha_g1_x.set(alpha_x_bytes.into());
        self.vk_alpha_g1_y.set(alpha_y_bytes.into());

        // Store beta G2
        let beta_x0_bytes: [u8; 32] = HARDCODED_VK_BETA_G2[0..32].try_into().unwrap();
        let beta_x1_bytes: [u8; 32] = HARDCODED_VK_BETA_G2[32..64].try_into().unwrap();
        let beta_y0_bytes: [u8; 32] = HARDCODED_VK_BETA_G2[64..96].try_into().unwrap();
        let beta_y1_bytes: [u8; 32] = HARDCODED_VK_BETA_G2[96..128].try_into().unwrap();
        self.vk_beta_g2_x0.set(beta_x0_bytes.into());
        self.vk_beta_g2_x1.set(beta_x1_bytes.into());
        self.vk_beta_g2_y0.set(beta_y0_bytes.into());
        self.vk_beta_g2_y1.set(beta_y1_bytes.into());

        // Store gamma G2
        let gamma_x0_bytes: [u8; 32] = HARDCODED_VK_GAMMA_G2[0..32].try_into().unwrap();
        let gamma_x1_bytes: [u8; 32] = HARDCODED_VK_GAMMA_G2[32..64].try_into().unwrap();
        let gamma_y0_bytes: [u8; 32] = HARDCODED_VK_GAMMA_G2[64..96].try_into().unwrap();
        let gamma_y1_bytes: [u8; 32] = HARDCODED_VK_GAMMA_G2[96..128].try_into().unwrap();
        self.vk_gamma_g2_x0.set(gamma_x0_bytes.into());
        self.vk_gamma_g2_x1.set(gamma_x1_bytes.into());
        self.vk_gamma_g2_y0.set(gamma_y0_bytes.into());
        self.vk_gamma_g2_y1.set(gamma_y1_bytes.into());

        // Store delta G2
        let delta_x0_bytes: [u8; 32] = HARDCODED_VK_DELTA_G2[0..32].try_into().unwrap();
        let delta_x1_bytes: [u8; 32] = HARDCODED_VK_DELTA_G2[32..64].try_into().unwrap();
        let delta_y0_bytes: [u8; 32] = HARDCODED_VK_DELTA_G2[64..96].try_into().unwrap();
        let delta_y1_bytes: [u8; 32] = HARDCODED_VK_DELTA_G2[96..128].try_into().unwrap();
        self.vk_delta_g2_x0.set(delta_x0_bytes.into());
        self.vk_delta_g2_x1.set(delta_x1_bytes.into());
        self.vk_delta_g2_y0.set(delta_y0_bytes.into());
        self.vk_delta_g2_y1.set(delta_y1_bytes.into());

        // Store gamma ABC length and points
        self.vk_gamma_abc_length.set(U256::from(HARDCODED_VK_GAMMA_ABC_G1.len()));
        for (i, point) in HARDCODED_VK_GAMMA_ABC_G1.iter().enumerate() {
            let x_bytes: [u8; 32] = point[0..32].try_into().unwrap();
            let y_bytes: [u8; 32] = point[32..64].try_into().unwrap();
            self.vk_gamma_abc_g1_x.setter(U256::from(i)).set(x_bytes.into());
            self.vk_gamma_abc_g1_y.setter(U256::from(i)).set(y_bytes.into());
        }

        self.vk_initialized.set(true);
        Ok(())
    }
}`;

// Write the verifying_key.rs file
const vkFilePath = path.join(__dirname, '..', 'contracts', 'src', 'verifying_key.rs');
fs.writeFileSync(vkFilePath, rustVkCode);

console.log('✅ Generated contracts/src/verifying_key.rs');
console.log('🎉 Contract is ready for compilation and deployment!');